### ISSUE TITLE
v0.20 - Music Room text for Shizuha's theme does not fit on screen

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#1]
As of a5c3cc79d087ec398f1b0155f290b171665ffcaf on MacOSX Mavericks, Wine 1.7.46, the :p in the Music Room text for Shizuha's theme cannot fit on the screen.

Solutions include removing the :p entirely, reducing side pitch (not recommended), or changing the font (not recommended), etc.

**Comment by ExPorygon** [comment]
It does for me. Screenshot?

**Comment by Sparen** [comment]
<img width="668" alt="screen shot 2015-09-01 at 8 52 34 am" src="https://cloud.githubusercontent.com/assets/5430590/9604640/d1c7d014-5086-11e5-85c4-e468494ee03e.png">

It's probably so minor it really doesn't matter

**Comment by ExPorygon** [comment]
I blame Macs.

**Comment by Sparen** [comment]
It's the way certain fonts are rendered. Usually they render wider on Windows, but this seems to be the opposite case.

Regardless, it's up to you if you want to keep the :p

**Comment by ExPorygon** [comment]
I lowered the font size by one. That's probably all I'm going to do.
