### ISSUE TITLE
v0.25 beta3 - Stage 3 is extremely hard on Easy Mode

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#10]
As of 42b9844035cf15cfba8e01c4bba4e799a31318bc, Stage 3 is significantly harder than the equivalent in a Touhou game, sans UFO. Upon comparison with other difficulties, it seems that there is little to no difference in the stage danmaku.

Is this a bug, balancing issue, or have other difficulties simply not been made for the stage?

**Comment by ExPorygon** [comment]
Stage 3 exists only on hard mode at the moment, as I mentioned before.
