### ISSUE TITLE
v0.25 beta4a - Path discrepancies

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#17]
As of 12680598f2dd1d7dedd4171a3b8d68a36e6d2cbf, and since the beginning of the project, there have been path discrepancies that are best fixed now rather than later.

I am referring to the capitalization of directories, such as SYSTEM and FONT. When referenced by other scripts in paths, I tend to see /System/ and /Font/. The problem here is that with archive files, Danmakufu treats paths as case-sensitive. 

IE: You have a file /SYSTEM/IMG/Image.png and you use the archiver to create Imgarchive.dat

Now you have /SYSTEM/Imgarchive.dat. However, Imgarchive.dat acts like IMG, so referring to the path System/Img/Image.png will fail to load the image because Danmakufu is looking for System/Img/Image.png when the archive loaded only has System/IMG/Image.png

This is currently low priority but if the decision is ever made to use archives, the entire game will break. The simplest way to remedy this is to change the folder names (e.g. SYSTEM) to how they are referenced by other scripts (e.g. System)

**Comment by ExPorygon** [comment]
I was not aware of this. I'll be adding a fix as archives were something I did want to use at some point.

**Comment by ExPorygon** [comment]
Added in 648c7e8e81238f58d2510b97c1449434011f2e8c.

**Comment by Sparen** [comment]
The folder names themselves have not changed though, so you still refer to /System/filename.ext when the 'System' folder is actually 'SYSTEM'

**Comment by ExPorygon** [comment]
Even though I DID change them. On my computer they're no longer all caps. I don't know how to get github to recognize that.

**Comment by Sparen** [comment]
How are you adding files before a commit?

**Comment by Sparen** [comment]
If you want me to do it, please tell me which folders have been renamed

**Comment by ExPorygon** [comment]
I didn't add any files, I just renamed the folders. The ones I renamed are Script, Font, System, Shot, Data, and Player.

**Comment by Sparen** [comment]
Did you commit the folder name changes to github, is the question

**Comment by ExPorygon** [comment]
For the last time YES.

**Comment by Sparen** [comment]
Danmakufu definitely complained about file names. 

Then again, since you can't archive a directory, I don't know how much Danmakufu cares when it comes to archives, if it cares at all.

**Comment by ExPorygon** [comment]
........If you're not even sure that folder names are a problem then why is this an issue at all?
