### ISSUE TITLE
v0.20 - Spell Bonus text spaz

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#2]
Currently, as of a5c3cc79d087ec398f1b0155f290b171665ffcaf, the spell bonus (during a spell card) text spazzes due to some numbers in the font not having the same width as others. 

To rectify, use a fixed width/monospace font (if using text objects), or correct the rects used (if using sprite lists)

**Comment by ExPorygon** [comment]
I fail to understand what you mean by "spazzing". If you mean the fact that the numbers "jump", that's an intended effect designed to be more similar to the animation that the spell card bonus number in the official games does. It was designed by gtbot and is also used in some of his things.

**Comment by Sparen** [comment]
See http://youtu.be/49qlaFvZGgc for what I mean by spazzing: See the first number in the Spellcard Bonus and how it moves from left to right depending on the widths of the following numbers

**Comment by ExPorygon** [comment]
I never even paid attention to that. I'll research how official touhou games handle it.
