### ISSUE TITLE
v0.25 beta4c - Lag Test.dnh crashes on startup

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#21]
Trying to open Lag Test.dnh results in the following error:

```
cannot file open path[Z:/Users/andrewfan/ssh/Ephemeral-Unnatural-Balance/System/System Prototype Minimal.dnh]
```

**Comment by ExPorygon** [comment]
I forgot that I had deleted System Prototype Minimal.dnh. Since that is the case, this file is deprecated and will be deleted. If I need to design a lag test script, I will redo it from scratch.
