### ISSUE TITLE
v0.25 beta4e - Stage 3 Orbs stay on screen

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#22]
In Stage 3, as of 5f89476a37ee6d8e429dc9bcfaa2197e9fafad92, there are some orbs that never leave the screen if they are never killed

<img width="640" alt="screen shot 2015-07-12 at 9 19 38 pm" src="https://cloud.githubusercontent.com/assets/5430590/8641172/a0846a56-28dd-11e5-96cd-bfc0515a356c.png">

This can be fixed by having them move offscreen and delete after a certain number of frames.

If unfixed, this issue can potentially cause problems with WaitForZeroEnemy.

**Comment by ExPorygon** [comment]
Fixed in 648c7e8e81238f58d2510b97c1449434011f2e8c.
