### ISSUE TITLE
v0.25 beta5a - Kasen's Options obscure ADD rendered bullets

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#25]
As of 09e6571ab9f7ebd34c2b1952804bed8e7d7ee04d, Kasen's options seem to render OVER bullets rather than under. This is not necessarily a major issue, per se, but they completely obscure certain bullet types, especially white bullets.

Fixable by changing render priority or alpha of options.

**Comment by ExPorygon** [comment]
This is not reproducible. Please specify the exact bullets that you witnessed the options rendering over.

**Comment by Sparen** [comment]
In the stage 1 opener, Kasen's white orb completely obscures all the bullets. It does not obscure the blue pellets, however. On closer inspection, this may have to do with the Blend Type of the bullets rather than the render priority, because if the round bullets are ADD rendered, it makes sense that they would be completely invisible underneath (or over) the option.

**Comment by Sparen** [comment]
Tested in cfa875ef346eff7cafb44f7a7a692da03ddbfbd7

**Comment by ExPorygon** [comment]
No player options are rendered ADD, the Kasen option must just be bright enough to cause problems in seeing bullets that are on top of them. I will try adjusting opacity.

**Comment by Sparen** [comment]
Adjusting Opacity should do the trick if it's not rendered using ADD.

**Comment by ExPorygon** [comment]
Adjusting the opacity really reduces the visual quality of the options. I was dissatisfied in lowering it to lower than 0.95. I will leave it as is for now to see if this is a widespread problem among players.
