### ISSUE TITLE
v0.20 - Poor contrast between bullets and Stage 1 Spell bg

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#3]
As of a5c3cc79d087ec398f1b0155f290b171665ffcaf, some of Futo's and Tojiko's bullets blend in with the spell background, which is quite bright. Especially in Tojiko's case, where you have yellow bullets on a partially yellow background.

Unfortunately, I do not know enough about Subtract Blend to aid in helping the problem, but you can use 

    ObjRender_SetColor(obj1, 192, 192, 192);

or something similar (SCRIPT/Stage 1/Stg1SpellBG.dnh, task SpellBG1) to darken the main portion of the background, though it may cause unwanted effects.

**Comment by ExPorygon** [comment]
Stage 1 spell bg is at this time too bright. Will be tweaking to improve contrast.
