### ISSUE TITLE
v0.28 beta2 - Stage opening fairies play alarm SFX upon death in Stage Practice

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#30]
As of cfa875ef346eff7cafb44f7a7a692da03ddbfbd7, in Stage Practice (via package), the Stage 1 and Stage 2 opener fairies (Only tested on Normal Mode) play the Alarm SFX upon death. Is this intentional?

Notes: 
-Playing as Rin Satsuki
-Only happens first time I play it. If I exit the package and play it again, it is fine.

**Comment by Sparen** [comment]
Note: Just to confirm, it ONLY happens when running from the package, and does not happen when running the stage files from the actual directories.

**Comment by ExPorygon** [comment]
Not intentional. The cause has been isolated and will be fixed in the next version.
