### ISSUE TITLE
v0.20 - Replay Breaking due to Default Lives, etc.

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#4]
As of a5c3cc79d087ec398f1b0155f290b171665ffcaf, the default lives effect setting breaks replays:

Currently, changing the default lives in config will change the lives in replay. One solution is to use replay comments to store the initial starting lives in the replay and load those lives in the package.

Fixing this is one component of allowing all replays to be rendered correctly regardless of existing config settings. All toggle able effect settings besides sound are vulnerable to replay desync if the settings the replay was recorded in are not preserved when running the replay.

**Comment by Sparen** [comment]
Update: WTF the replay didn't end when I was hit multiple times even though the dialogue scroll desynced the replay.

**Comment by ExPorygon** [comment]
I am aware of the need to store settings in replays to reload them during playback. However, the config  settings were not something I had remembered to include. This will be fixed.
