### ISSUE TITLE
v0.29 beta2 - Futo Midboss not optimized for Power Level

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#41]
As of e753ffbb45a1a941c5f7159d2f8af87d1f717386, the maximum possible power that can be gained in Stage 1 Normal before Futo is approximately 1.50-1.80 out of 4.00. With this power level, it is barely possible to clear Futo's attacks using Rin without dropping below the 10 second timer mark.

I suggest slightly lowering the HP of Futo's non spell and spell, but mainly the non spell. Not by too much, of course.

**Comment by ExPorygon** [comment]
This is intentional. Rin is the weakest shot type and the timers are kept low for stage purposes.
Fun Fact: EoSD does that with its stage 1 midboss, unless you're really good at following Rumia around. I don't see the timer going below 10 seconds as a bad thing.

**Comment by Sparen** [comment]
Oh, OK. Then this is fine, since there are still 10 seconds remaining in the best case scenario.
