### ISSUE TITLE
v0.29 beta3 - Perfect Balance and Extend notifications render at same location

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#43]
As of 7ac343e6c1703c750c7f35aafa8c53884a3568f0, the Perfect Balance and Extend notifications appear in the same location.

<img width="265" alt="screen shot 2015-09-05 at 9 17 40 pm" src="https://cloud.githubusercontent.com/assets/5430590/9701937/8f692674-5413-11e5-82f3-9b033a001a78.png">

**Comment by ExPorygon** [comment]
I honestly don't have a solution to this. I only have so many places on the screen that I can place these announcements so they don't overlap other things, I can't give each one a designated space. I already have Get Spell Card Bonus and similar notifications in a separate location as those come up a lot, but I can't do it for all of them. I don't know what to do with this for now, so I'm leaving the solution out of the Public Demo.

If you have any ideas for a reasonable solution, please share them.

**Comment by Kappatalist** [comment]
Obviously, who cares about this for the sake of the public demo, but what if you were to define a flag for each message which would be set to "true" when the message was displaying, and if two coincide, just draw the latter one lower/higher (or delete of the former one to make way, less ideal solution)?

**Comment by Sparen** [comment]
I believe delaying one of the messages until the former has deleted is the better idea.

**Comment by ExPorygon** [comment]
Looking back, I decided that implementing Sparen's idea is the best course of action. So I did, the next commit will include that fix.
