### ISSUE TITLE
v0.29 beta3 - Upon clearing the demo, Momiji's theme does not stop playing when returning to main menu

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#45]
As of 7ac343e6c1703c750c7f35aafa8c53884a3568f0, after clearing the demo, the game exits to the main menu without any replay save/whatever, and the bgm does not turn off. I.E. Momiji's Theme and the Main Menu theme are *both* playing at the same time on the main menu.

**Comment by ExPorygon** [comment]
Clearing should cause the end stage pause screen to appear as of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a. However, I have not tested this. The issue will remain open until verified.

**Comment by Sparen** [comment]
I am in the verification process at the moment. I will close the bug if it is fixed.

**Comment by Sparen** [comment]
Due to the black End? Scene appearing after Stage 3 closes, this bug is being marked as closed in d23f24d66fb2a1aac086082a5ce8a6f025dbd36a
