### ISSUE TITLE
Difficulty Balance Changes and Gameplay Tweaks

### ISSUE THREAD

**Issue by ExPorygon** [ExPorygon/Ephemeral-Unnatural-Balance#49]
In accordance with valuable playtesting feedback, numerous changes to attacks on different difficulty levels need to occur before the demo. Issue #26 falls under this issue as well.

**Comment by Sparen** [comment]
Note: Aya Midboss on Hard feels like Lunatic Mode (her spell especially). Compared to Momiji's first few attacks, Aya's spell feels out of place in terms of difficulty.

**Comment by Kappatalist** [comment]
Aya's first or second attack? On the second one I might be willing to agree, the randomness of the red/blue shots can wall you (although the changes to the green pattern have somewhat alleviated this), but the first attack is pretty cake (except in Discord, where it become totally insane).

**Comment by Sparen** [comment]
Her spell is what did me in. It's very restricting, and then super fast bullets wall you into a dense cluster of slower bullets if they don't outright kill you. I managed to survive one wave, but the max speed could be toned down just a little bit to make it less of a shock.
