### ISSUE TITLE
v0.20 - Allowed to save replay after continuing

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#5]
Currently, as of a5c3cc79d087ec398f1b0155f290b171665ffcaf, it is possible to save a replay after continuing.

**Comment by ExPorygon** [comment]
This is actually a feature, not a bug. With the continue setup I have, there's no reason that replays with continues can't happen. I've also added a handy display to the HUD to show how many continues a player has used during a replay.
