### ISSUE TITLE
v0.29 beta4 - Stage 2 Death Fairy on Easy is too difficult

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#50]
As of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a, the Stage 2 Death Fairy on Easy Mode spawns a large number of relatively fast bullets without warning. 

I recommend lowering the maximum speed slightly.

**Comment by ExPorygon** [comment]
I'm trying to remember which enemy you're referring to. As far as I remember, I don't have any single death fairy like enemies in that stage.

**Comment by Sparen** [comment]
It's the last enemy before the boss

**Comment by Kappatalist** [comment]
I think you're specifically referring to the side fairies who summon orange bullets everywhere. I do believe that may be a static pattern, but it's pretty hard to read and can catch the player off guard very easily. My opinion is that it ought to be visually a little less unorderly, and it should come in bursts to avoid piling too many bullets on screen. For stage 2, it's a bit intense.

**Comment by ExPorygon** [comment]
The idea of firing the shots in bursts is one that I'll try during tomorrow's stream.

**Comment by Sparen** [comment]
Confirming that there are actually two fairies shooting obscene abounds of bullets along with a laser fairy and not just one as I first thought.
