### ISSUE TITLE
v0.29 beta4 - Some spell card names do not fit on screen

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#51]
As of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a, some spell names do not fit on the screen, and they are not right-aligned. Perhaps use ALIGNMENT_RIGHT for a unified right bound?

<img width="330" alt="screen shot 2015-09-07 at 2 03 56 pm" src="https://cloud.githubusercontent.com/assets/5430590/9721515/7cf5c0a4-5569-11e5-9a80-213eabecc38c.png">

**Comment by ExPorygon** [comment]
They are right aligned. Maybe MACOSX causes that right align to not be where it should be somehow? I don't know what to do about this atm. For reference, the code section dealing with this is located in Effect.dnh at around line 1638 as of d23f24d66fb2a1aac086082a5ce8a6f025dbd36a.

**Comment by Sparen** [comment]
That's weird. I swear I saw one spell with the " being the last character, and this one has a different right alignment...

I'll take a look later.

**Comment by ExPorygon** [comment]
Apparently this is not just a MACOSX issue, but an issue introduced by Trickysticks possibly. More investigation is required.
