### ISSUE TITLE
v0.29 beta4c - Game crashes when stage or boss music file ends

### ISSUE THREAD

**Issue by Kappatalist** [ExPorygon/Ephemeral-Unnatural-Balance#56]
If the music in-game plays all the way to its end, Danmakufu crashes. That's about all there is to it.

**Comment by Sparen** [comment]
Please reference the commit

**Comment by Kappatalist** [comment]
fixed

**Comment by Sparen** [comment]
0.29 Beta 4D - unable to replicate bug. Marking as fixed.
