### ISSUE TITLE
v0.29 beta4c - Player shot effects do not delete after Player dies

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#57]
As of 03c5a23b88f591f06330cf689ca1b02fe2f2d212, when Rin (and perhaps Kasen as well) dies, the collision effects from her shots do not delete, animating in-place for an extended period of time.

Reported via stream, in existence for a number of versions beforehand.

**Comment by Kappatalist** [comment]
Kasen's shot graphics also have the ability to "linger".

**Comment by Sparen** [comment]
Still present in v0.29 beta4e @gtbot
