### ISSUE TITLE
v0.29 beta4e - Balance goes down during dialogues (Discord)

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#61]
As of 2d87bb50552f6fd3af0445f689e2b68387fb321c, Balance goes down during dialogue events (Discord Mode). 

I suggest pausing the decrease in Balance until the dialogue event has ended, or forcing the player to break out of Discord at the start of a dialogue event, possible refunding Balance points.

**Comment by Kappatalist** [comment]
I vote to freeze the player's gauge during dialogue events.
