### ISSUE TITLE
v0.29 beta5b - Shizuha Oracle of Seasons Spell (0,0) spawning error

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#62]
As of 3f34463f869df7c6b0ffcca7c38f10847a36068b, Shizuha's 'Oracle of Seasons - Sow the Seeds of Spring' spell displays (0,0) spawning errors on Hard Mode. Bubble bullets were deleted, and the strings that were supposed to form spawned from top left.

Note: I triggered discord mode at the start of the attack. Perhaps the forced deletion of bullets via Discord Mode was responsible?

**Comment by ExPorygon** [comment]
Bubble bullets were actually not deleted. The regular shots that they spawn were. I'll make them bomb immune or prevent them from spawning bullets if deleted.

**Comment by Kappatalist** [comment]
I vote make the bubbles bomb-immune, but their children bombable.
