### ISSUE TITLE
v0.30 - Kasen's options desync their attacks on power level up

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#65]
As of 23a94bb73ab1ff45e2fa30c3ff864c17c3de61df, Kasen's (and perhaps Rin's as well) options will desync upon power-level increasing. 

Reported initially by IHNN at 11:37 AM EST Sept 24, 2015 as follows:

Bug: Kasen's options can desync their firing (presumably Rin's too) when the power level increases: the new option will fire immediately, instead of synchronized with the existing options.

**Comment by Kappatalist** [comment]
Do they resynchronize if you stop firing and start firing again? If so, I'd argue this doesn't need to be fixed, since that may or may not be desirable for some players.
If it causes permanent desync, though, I'd agree that it needs to be fixed.

**Comment by jbardonjr** [comment]
They do resync if the player stops firing for any reason, but it's very visually jarring to suddenly see one option firing at a completely different time. I'm not sure how that would be desirable: it seems like the sort of thing that would annoy high level players by altering the standard damage rate, and for everyone else it looks like an obvious visual bug.

**Comment by Kappatalist** [comment]
Could just stop the player from firing until the next "shooting cycle" once they power-up, then.

**Comment by ExPorygon** [comment]
Oh I've been aware of this issue ever since I first made the players. I've just been putting off fixing it since I didn't have a good way to do it and I knew coming up with one would be annoying. Guess now's as good a time as any to finally fix it.

**Comment by ExPorygon** [comment]
This bug has actually been fixed in Version 0.31 c92e5324e9c756f8bc8768418459eefb3b8e8417
