### ISSUE TITLE
v0.30 - If Momiji's last spell ends during charge up phase, game locks to 45 FPS

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#66]
As of 23a94bb73ab1ff45e2fa30c3ff864c17c3de61df, if Momiji's last spell ends during the charge up phase, the game remains at 45 FPS.

Bug originally reported by IHNN at 11:43 AM EST Sept 24, 2015 as:

and I realized why my playthrough locked to 45 FPS

jeffrey-ihnn [11:44 AM]
If Momiji's Last Spell ends in the charge-up phase, nothing ever tells the game to go back to 60 FPS, so it stays at the slowed down 45.

jeffrey-ihnn [11:44 AM]
Not sure if this is just if you fail it or also on a capture, but it's definitely a bug

**Comment by Kappatalist** [comment]
Probably doesn't release the slowdown on spell end... ever. I'll try to look into it later tonight when I have time. I suspect I know exactly how and why this happens.

**Comment by Kappatalist** [comment]
Oh, there can only be one assignee. Uh, shoot.
