### ISSUE TITLE
v0.31 beta1 - Replays have 'Continues Used' item but always end where the first continue occurs

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#70]
As of d0e5533d8e00286a482adebd02104db9ca34a54f, replays have a 'continues used' note on the HUD, but since they always end at the first continue, the 'continues used' note is absolutely pointless.

**Comment by ExPorygon** [comment]
Unable to replicate this. This replay (http://puu.sh/kqR95/1a635694f6.dat) replay uses multiple continues and does not end early.

**Comment by Sparen** [comment]
Closing as invalid.
