### ISSUE TITLE
v0.41 beta1 - Bugs Regarding Stage 4

### ISSUE THREAD

**Issue by TheAgent17** [ExPorygon/Ephemeral-Unnatural-Balance#82]
**From what I saw with stage practice :**
> The stage music doesn't stop when opening the menu or during the boss fight.
> Pressing K messes with the background (makes black appear (fog removal ?) and some sort of background moving with each press).
> (Bullets should be deleted when the midboss dialogue starts, to avoid stupid deaths)

**Comment by ExPorygon** [comment]
The issues reported here are all fixed as of a04d4fdf96b483ed0203ccecdcf2f7c4485210c9.
