### ISSUE TITLE
Menus should scroll in the direction of the player's inputs

### ISSUE THREAD

**Issue by UltimaOmega** [ExPorygon/Ephemeral-Unnatural-Balance#83]
when pressing left it should always visually move left instead of moving right and vice versa

**Comment by ExPorygon** [comment]
Kind of forgot about this one, but essentially it was a symptom of not having all 3 players enabled. Now that Tokiko has been properly added as of b009a7cede8418b1a597781c6f8566995d6c2c81, this issue has been resolved.
