### ISSUE TITLE
Stage 4 notes (11/9/2016)

### ISSUE THREAD

**Issue by UltimaOmega** [ExPorygon/Ephemeral-Unnatural-Balance#84]
- Stage BGM doesn't stop ever, even during boss fights. (was tested in dnh's script menu)

- The fairies that travel in packs are too durable and trying to destroy them takes too long. More than likely requiring a bomb to be used.

- A bit dense for a stage 4 even for Hard mode sometimes. Could tune it down just a little.

- Background has visual issues that don't seem to be intended.

**Comment by ExPorygon** [comment]
Most of these concerns should be addressed in a04d4fdf96b483ed0203ccecdcf2f7c4485210c9. The visual bugs concerning the strange tree branches I'll open a new issue for
