### ISSUE TITLE
v0.43 beta2 - invalid Sound Effect is ear-splitting

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#88]
The sound effect used for when your aren't allowed to access a specific menu option is both loud and long, and if possible, I suggest it be replaced with a shorter and less ear-splitting sound effect.

**Comment by ExPorygon** [comment]
Sounds perfectly fine to me, but I'll settle for lowering its volume a little.

**Comment by Sparen** [comment]
I think the length is more of a problem than the volume, though both are a little too much imo.
