### ISSUE TITLE
v0.25 beta3 - Stage Practice does not grant more lives

### ISSUE THREAD

**Issue by Sparen** [ExPorygon/Ephemeral-Unnatural-Balance#9]
As of 42b9844035cf15cfba8e01c4bba4e799a31318bc, Stage Practice grants the same amount of lives as a normal play through rather than 10 lives (or whatever the maximum lives that can show on-screen is). This may be intentional or may be something left for the future.

**Comment by ExPorygon** [comment]
This will be implemented, it's actually in the design doc. I thought I had put it in already but I guess not.

**Comment by Sparen** [comment]
Reopening - As of 9f88f83c995846bdc10491ab2b1f5debd3092e5f, there are only 3 lives on Stage Practice by default. By opening the config settings, the amount of extra lives changes.
